<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-BFUTEFC0" ignored="0" name="TC_Logintest_001" tests="1" failures="1" timestamp="03 Dec 2020 00:39:03 GMT" time="22.638" errors="0">
  <testcase name="logintest" time="11.329" classname="com.ecommerce.testcases.TC_Logintest_001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.ecommerce.testcases.TC_Logintest_001.logintest(TC_Logintest_001.java:39)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- logintest -->
</testsuite> <!-- TC_Logintest_001 -->
